const esbuild = require('esbuild');

const production = process.argv.includes('--production');
const watch = process.argv.includes('--watch');

/**
 * @type {import('esbuild').Plugin}
 */
const esbuildProblemMatcherPlugin = {
  name: 'esbuild-problem-matcher',

  setup(build) {
    build.onStart(() => {
      console.log('[watch] build started');
    });

    build.onEnd((result) => {
      if (result.errors.length) {
        console.error('');
        result.errors.forEach(({ text, location }) => {
          const loc = location
            ? `${location.file}:${location.line}:${location.column}`
            : '<unknown>';
          console.error(`✘ [ERROR] ${text}`);
          console.error(`    ${loc}`);
        });
        console.error('');
        return;
      }

      if (result.warnings.length) {
        result.warnings.forEach(({ text, location }) => {
          const loc = location
            ? `${location.file}:${location.line}:${location.column}`
            : '<unknown>';
          console.warn(`▲ [WARN] ${text}`);
          console.warn(`    ${loc}`);
        });
      }

      console.log('[watch] build finished');
    });
  },
};

async function main() {
  const ctx = await esbuild.context({
    entryPoints: ['src/extension.ts'],
    bundle: true,
    format: 'cjs',
    minify: production,
    sourcemap: !production,
    sourcesContent: false,
    platform: 'node',
    target: 'node18',
    outfile: 'dist/extension.js',
    external: ['vscode'],
    logLevel: 'silent',
    metafile: true,
    banner: {
      js: '/* Generated by esbuild — do not edit. Source: src/extension.ts */',
    },
    plugins: [esbuildProblemMatcherPlugin],
  });

  if (watch) {
    await ctx.watch();
  } else {
    const result = await ctx.rebuild();
    await ctx.dispose();

    if (result.metafile) {
      const outputs = Object.entries(result.metafile.outputs);
      for (const [file, info] of outputs) {
        const kb = (info.bytes / 1024).toFixed(1);
        console.log(`  ${file}  ${kb} KB`);
      }
    }
  }
}

main().catch((err) => {
  console.error('[code-merge] build failed:');
  console.error(err);
  process.exit(1);
});